version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"

    # Batch dependencies into a single PR.
    groups:
      all-bun-deps:
        patterns:
          - "*"